CC = gcc
FLAG = -g -W

all:question1 question2

question1: question1.c
	${CC} ${FLAG} question1.c -o question1
question2: question2.c
	${CC} ${FLAG} question2.c -o question2

clean:
	rm question1 question2

